# Generated by Django 4.2.5 on 2023-10-05 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRushAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20, unique=True)),
                ('team_member', models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
