# Generated by Django 4.2.5 on 2023-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BRushAPI', '0002_user_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_twitch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
